# Generated by Django 4.1.3 on 2023-02-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_template', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navbar',
        ),
    ]
