# Generated by Django 4.1.3 on 2023-02-19 20:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_template', '0002_delete_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(default=False, upload_to='Title_Images')),
                ('Description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_Blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=False, upload_to='Blog_Images')),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_template.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='Category_Selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_template.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Language_Selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_template.language'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Section_Selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog_template.section'),
        ),
        migrations.CreateModel(
            name='Additional_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_by', models.CharField(max_length=150)),
                ('References', ckeditor.fields.RichTextField()),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_template.blog')),
            ],
        ),
    ]
